### YamlMime:ManagedReference
items:
- uid: WinForge.Settings.Application
  commentId: T:WinForge.Settings.Application
  id: Application
  parent: WinForge.Settings
  children:
  - WinForge.Settings.Application.LogFilePath
  - WinForge.Settings.Application.MaxLogFiles
  - WinForge.Settings.Application.ModuleDirectory
  langs:
  - csharp
  - vb
  name: Application
  nameWithType: Application
  fullName: WinForge.Settings.Application
  type: Class
  source:
    id: Application
    path: C:\Users\micha\source\repos\WinForge.Base\WinForge.Common\ApplicationSettings.cs
    startLine: 5
  assemblies:
  - WinForge.Common
  namespace: WinForge.Settings
  syntax:
    content: public static class Application
    content.vb: Public Module Application
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: WinForge.Settings.Application.ModuleDirectory
  commentId: P:WinForge.Settings.Application.ModuleDirectory
  id: ModuleDirectory
  parent: WinForge.Settings.Application
  langs:
  - csharp
  - vb
  name: ModuleDirectory
  nameWithType: Application.ModuleDirectory
  fullName: WinForge.Settings.Application.ModuleDirectory
  type: Property
  source:
    id: ModuleDirectory
    path: C:\Users\micha\source\repos\WinForge.Base\WinForge.Common\ApplicationSettings.cs
    startLine: 7
  assemblies:
  - WinForge.Common
  namespace: WinForge.Settings
  syntax:
    content: public static string ModuleDirectory { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property ModuleDirectory As String
  overload: WinForge.Settings.Application.ModuleDirectory*
- uid: WinForge.Settings.Application.LogFilePath
  commentId: P:WinForge.Settings.Application.LogFilePath
  id: LogFilePath
  parent: WinForge.Settings.Application
  langs:
  - csharp
  - vb
  name: LogFilePath
  nameWithType: Application.LogFilePath
  fullName: WinForge.Settings.Application.LogFilePath
  type: Property
  source:
    id: LogFilePath
    path: C:\Users\micha\source\repos\WinForge.Base\WinForge.Common\ApplicationSettings.cs
    startLine: 8
  assemblies:
  - WinForge.Common
  namespace: WinForge.Settings
  syntax:
    content: public static string LogFilePath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property LogFilePath As String
  overload: WinForge.Settings.Application.LogFilePath*
- uid: WinForge.Settings.Application.MaxLogFiles
  commentId: P:WinForge.Settings.Application.MaxLogFiles
  id: MaxLogFiles
  parent: WinForge.Settings.Application
  langs:
  - csharp
  - vb
  name: MaxLogFiles
  nameWithType: Application.MaxLogFiles
  fullName: WinForge.Settings.Application.MaxLogFiles
  type: Property
  source:
    id: MaxLogFiles
    path: C:\Users\micha\source\repos\WinForge.Base\WinForge.Common\ApplicationSettings.cs
    startLine: 9
  assemblies:
  - WinForge.Common
  namespace: WinForge.Settings
  syntax:
    content: public static int MaxLogFiles { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property MaxLogFiles As Integer
  overload: WinForge.Settings.Application.MaxLogFiles*
references:
- uid: WinForge.Settings
  commentId: N:WinForge.Settings
  href: WinForge.html
  name: WinForge.Settings
  nameWithType: WinForge.Settings
  fullName: WinForge.Settings
  spec.csharp:
  - uid: WinForge
    name: WinForge
    href: WinForge.html
  - name: .
  - uid: WinForge.Settings
    name: Settings
    href: WinForge.Settings.html
  spec.vb:
  - uid: WinForge
    name: WinForge
    href: WinForge.html
  - name: .
  - uid: WinForge.Settings
    name: Settings
    href: WinForge.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: WinForge.Settings.Application.ModuleDirectory*
  commentId: Overload:WinForge.Settings.Application.ModuleDirectory
  href: WinForge.Settings.Application.html#WinForge_Settings_Application_ModuleDirectory
  name: ModuleDirectory
  nameWithType: Application.ModuleDirectory
  fullName: WinForge.Settings.Application.ModuleDirectory
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: WinForge.Settings.Application.LogFilePath*
  commentId: Overload:WinForge.Settings.Application.LogFilePath
  href: WinForge.Settings.Application.html#WinForge_Settings_Application_LogFilePath
  name: LogFilePath
  nameWithType: Application.LogFilePath
  fullName: WinForge.Settings.Application.LogFilePath
- uid: WinForge.Settings.Application.MaxLogFiles*
  commentId: Overload:WinForge.Settings.Application.MaxLogFiles
  href: WinForge.Settings.Application.html#WinForge_Settings_Application_MaxLogFiles
  name: MaxLogFiles
  nameWithType: Application.MaxLogFiles
  fullName: WinForge.Settings.Application.MaxLogFiles
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
